steps:
# Step 1: Checkout the code from GitHub
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - 'git clone https://github.com/chandra1008adhi/cicdp1.git'

# Step 2: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/gcp-class-1-427416/cicdp1image:v1.0'
  - '.'

# Step 3: Push Docker image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/gcp-class-1-427416/cicdp1image:v1.0'

images:
- 'gcr.io/gcp-class-1-427416/cicdp1image:v1.0'
